[tool.poetry]
name = "curlify3"
version = "0.1.0"
description = ""
authors = ["A.Shpak <aleksander.shpak.als@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.115.4"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
requests = "^2.32.3"
httpx = "^0.27.2"
pytest = "^8.3.3"
responses = "^0.25.3"
pytest-asyncio = "^0.24.0"
pytest-httpx = "^0.33.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

